### PR TITLE
This builds and installs and runs !

### PR DESCRIPTION
**Pull request by ysalmon**
But column headers in the View have bizarre letters instead of field names.

### CODE REVIEW

**Comment by ysalmon** [comment]
Sorry, I was so happy to have it built at last.
screenshot - 08112015 - 18 51 43
These are indeed the initials of the field names. I get the same behaviour by double-clicking on a table, a view or by executing a SELECT statement in the script frame.
I can use field names correctly in WHERE clauses.
Exporting the data to SQL statements (using the 7th button in the interface) gives statements with truncated column names. The same happens with HTML export. But using the "Describe table" command gives the correct CREATE TABLE.
This happens with a new table in a new database too.

I cannot try with your sqlite version 3.9.1 because in the corresponding revision of the repo, there is no sqlite3.h file, which prevents building sqliteman (and my linux distro's version in package libsqlite-dev is 3.8). This is the reason I upgraded everything in the sqlite directory to 3.9.2 in the first place.

**Comment by rparkins999** [comment]
I have a feeling that this problem was caused by using the Qt internal SQL driver. Check the bottom right hand corner of the sqliteman window which should show the sqlite version actually in use (should be 3.9.2 if you're using that).
Try this commandcmake -DWANT_DEBUG=1 -DWANT_RESOURCES=1 -DWANT_INTERNAL_QSCINTILLA=1 -DWANT_INTERNAL_SQLDRIVER=0 .
in the Sqliteman directory (not the sqliteman subdirectory) and then try building it again.
Richard

**Comment by ysalmon** [comment]
Setting -DWANT_INTERNAL_SQLDRIVER=0 prevents the problem from happening. Note that the version number in the bottom right corner is 3.9.2, with or without setting this configuration switch.

**Pull request merged**
